### ISSUE TITLE
Discrepancy in calculated fractional index.

### ISSUE THREAD

**Issue by iamsaumya** [goabstract/fractional-index#1]
From my understanding, 

```js
"a" < fractionalIndex("a","b") //true
"b" > fractionalIndex("a","b") //true

fractionalIndex(null,"a") < "a" //true

fractionalIndex("a",null) > "a" //true
```

However, there is a bug when we do 

```js
const val = fractionalIndex(null,"!") // P

val < "!" //false, but index should be smaller.
```

Also

```js
fractionalIndex(null,"!") //P
fractionalIndex("!",null) // is also P 
```

NB: There may be many more scenarios where the index may fail but this is the only case I can reproduce.

**Comment by Venryx** [comment]
Are you sure `!` is a valid character for use in the string input? My understanding from the source document (https://observablehq.com/@dgreensp/implementing-fractional-indexing) is that the default characters used are restricted to:
```
BASE_62_DIGITS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
```

So, it maybe is normal that it will give unexpected outputs when you pass in characters it doesn't accept as valid. (granted, it should probably throw an error or warning in that case)

**EDIT**: By the way, you can also try this JS implementation of the algorithm instead (it's the one I use): https://github.com/rocicorp/fractional-indexing

**Comment by iamsaumya** [comment]
Yes. This was a mistake on my end
